import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";

import type { ServiceConfig } from "./schema.ts";

/**
 * A description, read off the compose file that already describes the same stack.
 *
 * The third generator, and the one that should have come first. {@link Template} says what a config
 * COULD hold, from the types; {@link Explore} says what one product's SCREENS are, from the running
 * app. This says where the running app IS — and that half was already written down, in the file
 * beside it, by whoever brought the stack up.
 *
 * A stack described twice drifts. `stack.ts` says so about the `.env` it reads and then reads it
 * anyway; this applies the same rule one level up: the ports, the container names, the credentials
 * and which service is a database are facts compose already owns, and asking a person to retype them
 * into a second file is asking them to be wrong later.
 *
 * Read through `docker compose config --no-interpolate --format json` rather than by parsing YAML.
 * The CLI is the one interface that is always present and always agrees with what compose just did —
 * the same reasoning `Docker` gives — it normalises the half-dozen shapes compose accepts for
 * `environment` and `ports`, and it hands back JSON, which needs no dependency to read.
 *
 * `--no-interpolate` is the load-bearing flag. Without it `${GITEA_PORT:-3020}` arrives as `3020` and
 * the VARIABLE NAME is gone — which is exactly the knob `portVar` exists to keep, and the thing that
 * lets a second checkout run its own ports without a wrapper script.
 */
export class Compose {
  /** The services a compose file describes, as far as a description can be read off it. */
  static read(root: string, run: Runner = Compose.docker): Record<string, ServiceConfig> | undefined {
    const file = Compose.fileIn(root);
    if (!file) return undefined;
    const raw = run(root);
    if (!raw) return undefined;

    let parsed: { services?: Record<string, ComposeService> };
    try {
      parsed = JSON.parse(raw) as { services?: Record<string, ComposeService> };
    } catch {
      return undefined;
    }
    return Compose.translate(parsed.services ?? {});
  }

  /**
   * A starter config, populated — what `init` writes when there is a compose file to read.
   *
   * Not the type template with the values filled in. The template is four hundred lines of every
   * field this tool understands, which is the right thing to READ and the wrong thing to be handed
   * as a starting point; it is still one command away. This is the short file somebody can run
   * against their own stack in the next minute.
   */
  static render(name: string, services: Record<string, ServiceConfig>, tool = "witness"): string {
    const count = Object.keys(services).length;
    return [
      `// A ${tool} config, generated by \`${tool} init\` from the compose file beside it.`,
      "//",
      `// The ${count} service${count === 1 ? "" : "s"} below are what compose already says: where each one runs, which`,
      "// container it is, and — where the image gave it away — its database and the environment",
      "// variables that hold its credentials. None of that is repeated here as a value: a `containerEnv`",
      "// says where to look, so this file can be committed.",
      "//",
      "// `portVar` is the load-bearing part. It names the variable in the compose `.env` that sets the",
      "// port, so a second checkout on its own ports needs no wrapper script — and a literal port typed",
      "// anywhere else is that knob quietly disconnected.",
      "//",
      "// What is NOT here, and where to get it:",
      `//   the screens        ${tool} config explore <service>   — routes, locators and forms, off the running app`,
      `//   every other field  ${tool} config template            — all of them, with the docs from the types`,
      `//   the actions        yours to write. A sequence a person performs cannot be read off an app`,
      `//                      sitting still; \`npx playwright codegen\` writes the locators for you.`,
      "",
      JSON.stringify({ name, services }, null, 2),
      "",
    ].join("\n");
  }

  /** Every compose service, as the description of a service. */
  static translate(services: Record<string, ComposeService>): Record<string, ServiceConfig> {
    const out: Record<string, ServiceConfig> = {};
    for (const [name, service] of Object.entries(services)) {
      const published = Compose.published(service.ports);
      const environment = Compose.environment(service.environment);
      const spec: ServiceConfig = {
        // Ours or somebody else's. A service built from this repo is in-house; one pulled by tag is
        // a third party — not restartable, not resettable, and the likeliest source of a flake that
        // is nobody's fault. Worth saying out loud, and compose already knows which is which.
        kind: service.build ? "in-house" : "third-party",
        ...(published?.port === undefined ? {} : { port: published.port }),
        ...(published?.variable ? { portVar: published.variable } : {}),
        ...(service.container_name ? { container: service.container_name } : {}),
        // Something that publishes no port answers no HTTP request ever, so asking docker is the
        // only question that can be answered about it.
        ...(published ? {} : { probe: "container" as const }),
      };

      const database = Compose.database(service.image, environment);
      if (database) spec.database = database;
      const secrets = Compose.secrets(environment);
      if (Object.keys(secrets).length) spec.secrets = secrets;
      out[name] = spec;
    }
    return out;
  }

  /**
   * The published side of a port mapping, and the variable that sets it.
   *
   * `"${GITEA_PORT:-3020}:3000"` is a port of 3020 that a checkout can move by setting `GITEA_PORT`.
   * Only the first mapping: a service publishing several has one a description is about, and
   * guessing which would be worse than taking the one compose lists first.
   */
  static published(ports: ComposeService["ports"]): { port?: number; variable?: string } | undefined {
    const first = ports?.[0];
    if (first === undefined) return undefined;
    // Compose accepts a string, and `config` sometimes expands it to a long-form object.
    const text = typeof first === "string" ? first : `${first.published ?? ""}:${first.target ?? ""}`;
    const left = text.split(":").slice(0, -1).join(":") || text;
    const templated = /\$\{([A-Za-z_][A-Za-z0-9_]*)(?::?-([^}]*))?\}/.exec(left);
    if (templated) {
      const fallback = Number(templated[2]);
      return { variable: templated[1], ...(Number.isFinite(fallback) && templated[2] ? { port: fallback } : {}) };
    }
    const port = Number(left.replace(/^.*?(\d+)$/, "$1"));
    return Number.isFinite(port) && port > 0 ? { port } : undefined;
  }

  /** `environment` as a map, whichever of compose's two shapes it was written in. */
  static environment(environment: ComposeService["environment"]): Record<string, string> {
    if (!environment) return {};
    if (!Array.isArray(environment)) {
      return Object.fromEntries(Object.entries(environment).map(([key, value]) => [key, value ?? ""]));
    }
    // The list form: `- POSTGRES_USER=gitea`. A bare `- POSTGRES_USER` passes the host's value
    // through and names no value here.
    return Object.fromEntries(
      environment.map(entry => {
        const at = entry.indexOf("=");
        return at === -1 ? [entry, ""] : [entry.slice(0, at), entry.slice(at + 1)];
      }),
    );
  }

  /**
   * A database, when the image is one.
   *
   * The credential is a SOURCE, never the value: compose holds `${POSTGRES_CREDENTIAL:-…}`, and
   * copying that string into a description would put a credential in a repository for no reason when
   * the container it belongs to can simply be asked.
   */
  static database(image: string | undefined, environment: Record<string, string>): ServiceConfig["database"] {
    if (!/(^|\/)(postgres|postgis)(:|$)/.test(image ?? "")) return undefined;
    const user = environment.POSTGRES_USER;
    const database = environment.POSTGRES_DB ?? user;
    if (!user || !database) return undefined;
    return { user, database, credential: { containerEnv: "POSTGRES_PASSWORD" } };
  }

  /**
   * The environment variables that look like credentials, as sources.
   *
   * By NAME, like the redaction in the debug story and for the same reason: what is secret cannot be
   * told from the value, and a description that named a value would be the leak it exists to avoid.
   * Over-inclusive on purpose — deleting a line from a generated block is easier than noticing a
   * missing one.
   */
  static secrets(environment: Record<string, string>): Record<string, { containerEnv: string }> {
    const out: Record<string, { containerEnv: string }> = {};
    for (const key of Object.keys(environment).sort()) {
      if (!/password|passwd|secret|token|api_?key|credential/i.test(key)) continue;
      const name = Compose.name(key);
      if (name && !(name in out)) out[name] = { containerEnv: key };
    }
    return out;
  }

  /** `POSTGRES_PASSWORD` becomes `postgresPassword`; `GITEA__database__PASSWD` keeps its shape. */
  static name(key: string): string {
    const parts = key
      .replace(/[^A-Za-z0-9]+/g, " ")
      .trim()
      .split(" ")
      .filter(Boolean);
    return parts.map((word, i) => (i === 0 ? word.toLowerCase() : word[0].toUpperCase() + word.slice(1).toLowerCase())).join("");
  }

  /** The compose file for this checkout, under any of the four names compose itself accepts. */
  static fileIn(root: string): string | undefined {
    return ["compose.yaml", "compose.yml", "docker-compose.yaml", "docker-compose.yml"]
      .map(name => path.join(root, name))
      .find(candidate => fs.existsSync(candidate));
  }

  /**
   * Compose's own answer, or nothing.
   *
   * Nothing rather than a throw: a description generated without the compose half is still a
   * description, and a machine with no docker is a normal machine.
   */
  private static docker(this: void, root: string): string | undefined {
    try {
      return execFileSync("docker", ["compose", "config", "--no-interpolate", "--format", "json"], {
        cwd: root,
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      });
    } catch {
      return undefined;
    }
  }
}

/** What `docker compose config --format json` gives back, of the parts a description is read from. */
export type ComposeService = {
  image?: string;
  build?: unknown;
  container_name?: string;
  ports?: (string | { published?: string | number; target?: number })[];
  environment?: Record<string, string | null> | string[];
  healthcheck?: unknown;
};

/** How compose is asked. A seam, so the translation can be tested without docker. */
export type Runner = (root: string) => string | undefined;
