import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";

import type { ServiceConfig } from "./schema.ts";

/**
 * A description, read off the compose file that already describes the same stack.
 *
 * The third generator, and the one that should have come first. {@link Template} says what a config
 * COULD hold, from the types; {@link Explore} says what one product's SCREENS are, from the running
 * app. This says where the running app IS — and that half was already written down, in the file
 * beside it, by whoever brought the stack up.
 *
 * A stack described twice drifts. `stack.ts` says so about the `.env` it reads and then reads it
 * anyway; this applies the same rule one level up: the ports, the container names, the credentials
 * and which service is a database are facts compose already owns, and asking a person to retype them
 * into a second file is asking them to be wrong later.
 *
 * Read through `docker compose config --no-interpolate --format json` rather than by parsing YAML.
 * The CLI is the one interface that is always present and always agrees with what compose just did —
 * the same reasoning `Docker` gives — it normalises the half-dozen shapes compose accepts for
 * `environment` and `ports`, and it hands back JSON, which needs no dependency to read.
 *
 * `--no-interpolate` is the load-bearing flag. Without it `${GITEA_PORT:-3020}` arrives as `3020` and
 * the VARIABLE NAME is gone — which is exactly the knob `portVar` exists to keep, and the thing that
 * lets a second checkout run its own ports without a wrapper script.
 */
export class Compose {
  /** The stack a compose file describes, as far as a description can be read off it. */
  static read(root: string, run: Runner = Compose.docker): ComposeDescription | undefined {
    const file = Compose.fileIn(root);
    if (!file) return undefined;
    const raw = run(root);
    if (!raw) return undefined;

    let parsed: { name?: string; services?: Record<string, ComposeService> };
    try {
      parsed = JSON.parse(raw) as { name?: string; services?: Record<string, ComposeService> };
    } catch {
      return undefined;
    }
    // The project name, which most services never mention because compose supplies it — and which is
    // in the same document, so a container nobody named is still a container this can work out.
    return Compose.translate(parsed.services ?? {}, parsed.name);
  }

  /**
   * A starter config, populated — what `init` writes when there is a compose file to read.
   *
   * Not the type template with the values filled in. The template is four hundred lines of every
   * field this tool understands, which is the right thing to READ and the wrong thing to be handed
   * as a starting point; it is still one command away. This is the short file somebody can run
   * against their own stack in the next minute.
   */
  static render(name: string, read: ComposeDescription, tool = "witness"): string {
    const { services, suffixVar } = read;
    const count = Object.keys(services).length;
    // Said only when it fired. Which database `db sql` means is decided by the ORDER below, and a
    // reader who tidies that order back into alphabetical would repoint it silently.
    const withDatabase = Object.entries(services)
      .filter(([, service]) => service.database)
      .map(([serviceName]) => serviceName);
    return [
      `// A ${tool} config, generated by \`${tool} init\` from the compose file beside it.`,
      "//",
      `// The ${count} service${count === 1 ? "" : "s"} below are what compose already says: where each one runs, which`,
      "// container it is, and — where the image gave it away — its database and the environment",
      "// variables that hold its credentials. None of that is repeated here as a value: a `containerEnv`",
      "// says where to look, so this file can be committed.",
      "//",
      "// `portVar` is the load-bearing part. It names the variable in the compose `.env` that sets the",
      "// port, so a second checkout on its own ports needs no wrapper script — and a literal port typed",
      "// anywhere else is that knob quietly disconnected.",
      ...(withDatabase.length > 1
        ? [
            "//",
            `// ${withDatabase.length} databases, and \`${tool} db sql\` runs against the FIRST one listed — ${withDatabase[0]}. The`,
            "// order is the compose file's `depends_on`, not alphabetical: a database the app says it needs",
            `// comes before one nothing mentions. Reach the others with \`--on=<service>\`, and if the wrong`,
            "// one is first, move it here.",
          ]
        : []),
      "//",
      "// What is NOT here, and where to get it:",
      `//   the screens        ${tool} config explore <service>   — routes, locators and forms, off the running app`,
      `//   every other field  ${tool} config template            — all of them, with the docs from the types`,
      `//   the actions        yours to write. A sequence a person performs cannot be read off an app`,
      `//                      sitting still; \`npx playwright codegen\` writes the locators for you.`,
      "",
      JSON.stringify({ name, ...(suffixVar ? { suffixVar } : {}), services }, null, 2),
      "",
    ].join("\n");
  }

  /** Every compose service, as the description of a service — and what the whole file implies. */
  static translate(services: Record<string, ComposeService>, project?: string): ComposeDescription {
    const out: Record<string, ServiceConfig> = {};
    const suffixes = new Set<string>();
    for (const [name, service] of Compose.appDatabaseFirst(services)) {
      const published = Compose.published(service.ports);
      const environment = Compose.environment(service.environment);
      const runsAs = Compose.container(service.container_name, name, project);
      if (runsAs?.variable) suffixes.add(runsAs.variable);
      const spec: ServiceConfig = {
        // Ours or somebody else's. `build:` is evidence of in-house; its ABSENCE is evidence of
        // nothing — a stack that builds its images in CI and pulls them back by tag would be
        // labelled third-party from end to end, which inverts the meaning of the field for every
        // service in it. `kind` says a service is not restartable, not resettable and shared, so
        // saying it wrongly is worse than not saying it: an absent field is honest.
        ...(service.build ? { kind: "in-house" as const } : {}),
        ...(published?.port === undefined ? {} : { port: published.port }),
        ...(published?.variable ? { portVar: published.variable } : {}),
        ...(runsAs?.container ? { container: runsAs.container } : {}),
        // A published port is not an HTTP port. Something that publishes none answers no HTTP request
        // ever — and neither does a database or a broker that publishes one, so nothing at
        // `http://localhost:5441` will pass the default probe however long it is given. Docker is the
        // only question that can be answered about either.
        ...(published && Compose.speaksHttp(service.image) ? {} : { probe: "container" as const }),
      };

      const database = Compose.database(service.image, environment);
      if (database) spec.database = database;
      const secrets = Compose.secrets(environment);
      if (Object.keys(secrets).length) spec.secrets = secrets;
      out[name] = spec;
    }
    // Only when the file agrees with itself. Two different variables suffixing two different services
    // is not the worktree convention this names, and guessing which one is meant would be worse than
    // leaving the names as compose wrote them.
    const [only] = suffixes;
    return { services: out, ...(suffixes.size === 1 ? { suffixVar: only } : {}) };
  }

  /**
   * Where compose actually runs a service, and the variable a second checkout moves it with.
   *
   * Two things go wrong here and they are the same thing twice. `container_name: hesta-api${WT:-}`
   * transcribed as text names a container that does not exist and never will, so the service reports
   * DOWN whatever is running — while `suffixVar` is the knob that already expresses exactly this, the
   * way `portVar` does for ports. And a service with NO `container_name` is not a service with no
   * container: compose names it `<project>-<service>-1`, off the project in this same document.
   */
  static container(declared: string | undefined, service: string, project?: string): { container?: string; variable?: string } | undefined {
    if (!declared) return project ? { container: `${project}-${service}-1` } : undefined;
    const suffixed = /^(.*?)\$\{([A-Za-z_][A-Za-z0-9_]*)(?::?-[^}]*)?\}$/.exec(declared);
    return suffixed ? { container: suffixed[1], variable: suffixed[2] } : { container: declared };
  }

  /**
   * Whether a published port is one an HTTP probe can ask anything of.
   *
   * By image, because that is the only thing in the file that says what protocol is on the port.
   * Over-inclusive in the safe direction: an unrecognised image is assumed to speak HTTP, which is
   * the default a person would have written anyway.
   */
  static speaksHttp(image: string | undefined): boolean {
    return !/(^|\/)(postgres(ql)?|postgis|mysql|mariadb|redis|valkey|memcached|mongo(db)?|clickhouse(-server)?|cassandra|kafka|zookeeper|rabbitmq|nats)(:|$)/.test(image ?? "");
  }

  /**
   * The published side of a port mapping, and the variable that sets it.
   *
   * `"${GITEA_PORT:-3020}:3000"` is a port of 3020 that a checkout can move by setting `GITEA_PORT`.
   * Only the first mapping: a service publishing several has one a description is about, and
   * guessing which would be worse than taking the one compose lists first.
   */
  static published(ports: ComposeService["ports"]): { port?: number; variable?: string } | undefined {
    const first = ports?.[0];
    if (first === undefined) return undefined;
    // Compose accepts a string, and `config` sometimes expands it to a long-form object.
    const text = typeof first === "string" ? first : `${first.published ?? ""}:${first.target ?? ""}`;
    const left = text.split(":").slice(0, -1).join(":") || text;
    const templated = /\$\{([A-Za-z_][A-Za-z0-9_]*)(?::?-([^}]*))?\}/.exec(left);
    if (templated) {
      const fallback = Number(templated[2]);
      return { variable: templated[1], ...(Number.isFinite(fallback) && templated[2] ? { port: fallback } : {}) };
    }
    const port = Number(left.replace(/^.*?(\d+)$/, "$1"));
    return Number.isFinite(port) && port > 0 ? { port } : undefined;
  }

  /** `environment` as a map, whichever of compose's two shapes it was written in. */
  static environment(environment: ComposeService["environment"]): Record<string, string> {
    if (!environment) return {};
    if (!Array.isArray(environment)) {
      return Object.fromEntries(Object.entries(environment).map(([key, value]) => [key, value ?? ""]));
    }
    // The list form: `- POSTGRES_USER=gitea`. A bare `- POSTGRES_USER` passes the host's value
    // through and names no value here.
    return Object.fromEntries(
      environment.map(entry => {
        const at = entry.indexOf("=");
        return at === -1 ? [entry, ""] : [entry.slice(0, at), entry.slice(at + 1)];
      }),
    );
  }

  /**
   * A database, when the image is one.
   *
   * The credential is a SOURCE, never the value: compose holds `${POSTGRES_CREDENTIAL:-…}`, and
   * copying that string into a description would put a credential in a repository for no reason when
   * the container it belongs to can simply be asked.
   */
  /**
   * The services, with a database nothing says it needs moved below one something does.
   *
   * `db sql` runs against the FIRST service to declare a database — the same rule `api` uses for
   * clients — and `docker compose config` hands the services back alphabetically. On a stack holding
   * both a MariaDB and a Postgres that made **mariadb** the default by sorting accident, so a bare
   * `db sql` ran `psql` inside MariaDB. Nothing about the description said which one the app used;
   * the letter `m` did.
   *
   * The compose file already answers it, and answering it from there is what this whole class is for:
   * a database the app `depends_on` is the app's database. Where the file says nothing — no
   * `depends_on` anywhere, which is most compose files — nothing here can know either, and the order
   * stays exactly as compose gave it for the author to change. A wrong guess in a generated file is
   * worse than an order somebody has to look at.
   *
   * Stable, and only databases move: every other service keeps the place it had.
   */
  private static appDatabaseFirst(services: Record<string, ComposeService>): [string, ComposeService][] {
    const needed = new Set(Object.values(services).flatMap(service => Compose.dependsOn(service)));
    const entries = Object.entries(services);
    const isDatabase = ([, service]: [string, ComposeService]): boolean =>
      Boolean(Compose.database(service.image, Compose.environment(service.environment)));
    // Only when there is somewhere to move one TO. With no `depends_on` anywhere, every database is
    // unmentioned and sinking them all would reorder the file for no reason and answer nothing.
    if (!entries.filter(isDatabase).some(([name]) => needed.has(name))) return entries;
    const orphan = (entry: [string, ComposeService]): boolean => isDatabase(entry) && !needed.has(entry[0]);
    return [...entries.filter(entry => !orphan(entry)), ...entries.filter(orphan)];
  }

  /** What a service says it needs. Compose normalises to an object; a hand-written file may be a list. */
  private static dependsOn(service: ComposeService): string[] {
    return Array.isArray(service.depends_on) ? service.depends_on : Object.keys(service.depends_on ?? {});
  }

  static database(image: string | undefined, environment: Record<string, string>): ServiceConfig["database"] {
    const engine = DATABASES.find(known => known.image.test(image ?? ""));
    if (!engine) return undefined;
    const value = (keys: string[]): string | undefined => keys.map(key => environment[key]).find(Boolean);
    const user = value(engine.user);
    const database = value(engine.database) ?? user;
    if (!user || !database) return undefined;
    // The variable that is actually SET, so the container can be asked for it by the name it has.
    const credential = engine.credential.find(key => key in environment) ?? engine.credential[0];
    return { user, database, credential: { containerEnv: credential } };
  }

  /**
   * The environment variables that look like credentials, as sources.
   *
   * By NAME, like the redaction in the debug story and for the same reason: what is secret cannot be
   * told from the value, and a description that named a value would be the leak it exists to avoid.
   * Over-inclusive on purpose — deleting a line from a generated block is easier than noticing a
   * missing one.
   */
  static secrets(environment: Record<string, string>): Record<string, { containerEnv: string }> {
    const out: Record<string, { containerEnv: string }> = {};
    for (const key of Object.keys(environment).sort()) {
      if (!/password|passwd|secret|token|api_?key|credential/i.test(key)) continue;
      const name = Compose.name(key);
      if (name && !(name in out)) out[name] = { containerEnv: key };
    }
    return out;
  }

  /** `POSTGRES_PASSWORD` becomes `postgresPassword`; `GITEA__database__PASSWD` keeps its shape. */
  static name(key: string): string {
    const parts = key
      .replace(/[^A-Za-z0-9]+/g, " ")
      .trim()
      .split(" ")
      .filter(Boolean);
    return parts.map((word, i) => (i === 0 ? word.toLowerCase() : word[0].toUpperCase() + word.slice(1).toLowerCase())).join("");
  }

  /** The compose file for this checkout, under any of the four names compose itself accepts. */
  static fileIn(root: string): string | undefined {
    return ["compose.yaml", "compose.yml", "docker-compose.yaml", "docker-compose.yml"]
      .map(name => path.join(root, name))
      .find(candidate => fs.existsSync(candidate));
  }

  /**
   * Compose's own answer, or nothing.
   *
   * Nothing rather than a throw: a description generated without the compose half is still a
   * description, and a machine with no docker is a normal machine.
   *
   * `exec` is here so a test can read the argv rather than the answer. Every other test in this file
   * hands `read` a runner and never reaches this line, so the one flag the whole generator depends on
   * had nothing checking it: dropping `--no-interpolate` left 424 tests passing and every generated
   * config silently without its `portVar`, which only shows up on the second checkout — the exact case
   * `portVar` exists for.
   */
  static docker(this: void, root: string, exec: typeof execFileSync = execFileSync): string | undefined {
    try {
      return exec("docker", ["compose", "config", "--no-interpolate", "--format", "json"], {
        cwd: root,
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      });
    } catch {
      return undefined;
    }
  }
}

/**
 * The database images a description can be read off, and where each one keeps its credentials.
 *
 * Postgres was the only entry, so a stack with a MariaDB in it had its database name, its user and
 * the variable holding its password sitting in the compose file being ignored — and the whole
 * database went undescribed. Both prefixes for MySQL-family images: the MariaDB image reads either,
 * and a compose file written for one image and run on the other is a normal thing to find.
 */
const DATABASES = [
  { image: /(^|\/)(postgres(ql)?|postgis)(:|$)/, user: ["POSTGRES_USER"], database: ["POSTGRES_DB"], credential: ["POSTGRES_PASSWORD"] },
  {
    image: /(^|\/)(mysql|mariadb)(:|$)/,
    user: ["MARIADB_USER", "MYSQL_USER"],
    database: ["MARIADB_DATABASE", "MYSQL_DATABASE"],
    credential: ["MARIADB_PASSWORD", "MYSQL_PASSWORD"],
  },
];

/** A whole compose file, as a description: the services, and what the file says about all of them. */
export type ComposeDescription = {
  services: Record<string, ServiceConfig>;
  /** The variable a checkout suffixes its container names with — compose's `${WT:-}`, as a knob. */
  suffixVar?: string;
};

/** What `docker compose config --format json` gives back, of the parts a description is read from. */
export type ComposeService = {
  image?: string;
  build?: unknown;
  container_name?: string;
  ports?: (string | { published?: string | number; target?: number })[];
  environment?: Record<string, string | null> | string[];
  /** Which service is the app's database, when the file says so. See {@link Compose.appDatabaseFirst}. */
  depends_on?: string[] | Record<string, unknown>;
  healthcheck?: unknown;
};

/** How compose is asked. A seam, so the translation can be tested without docker. */
export type Runner = (root: string) => string | undefined;
