import * as fs from "node:fs";
import * as path from "node:path";

import * as providers from "../providers/index.ts";
import { Registry } from "../providers/registry.ts";
import { TypeSource, type TypeField, type TypeModel } from "./types.ts";

/**
 * A config file's template, generated from the types that read it.
 *
 * Nothing here is a list of what witness supports — every list is asked for at the moment the template
 * is printed: the fields come from the type declarations, the provider names from the registries
 * themselves. Add a field, register a provider, and the next `witness config template` says so without
 * anyone remembering to update an example.
 *
 * The output is JSONC — the doc comment on each field, above the field — and `loadConfig` reads
 * comments, so what comes out is a config file you can start editing rather than a picture of one.
 */
export class Template {
  private readonly types: TypeSource;
  private readonly registered: Map<string, string[]>;
  private readonly maxDepth: number;
  /** Named types already spelled out in full, and where — the second one points at the first. */
  private shown = new Map<string, string>();

  constructor(opts: { types: TypeSource; providers?: Map<string, string[]>; maxDepth?: number }) {
    this.types = opts.types;
    this.registered = opts.providers ?? new Map();
    this.maxDepth = opts.maxDepth ?? 8;
  }

  /** The template for THIS copy of witness: its own type declarations, its own registered providers. */
  static forWitness(sourceDir = Template.sourceDir()): Template {
    return new Template({ types: TypeSource.fromDirectory(sourceDir), providers: Template.providers() });
  }

  /**
   * The TypeScript this copy was written in — which is what the template is generated from.
   *
   * Running from the sources that is the directory above this file. Running from a published package it
   * is the `src/` shipped beside the build: the types are the description of the config, so they travel
   * with it rather than being compiled away.
   */
  static sourceDir(from = import.meta.dirname): string {
    const candidates = [path.join(from, ".."), path.join(from, "..", "..", "..", "src")];
    const found = candidates.find(at => fs.existsSync(path.join(at, "config", "schema.ts")));
    if (!found) throw new Error(`no witness sources beside ${from} — looked in ${candidates.join(", ")}`);
    return found;
  }

  /**
   * Every provider registry the package exports, by kind.
   *
   * Found rather than listed: a registry is recognisable at runtime, so a sixth kind of provider needs
   * no edit here to appear in the template.
   */
  static providers(from: Record<string, unknown> = providers as unknown as Record<string, unknown>): Map<string, string[]> {
    const found = new Map<string, string[]>();
    for (const value of Object.values(from)) {
      if (value instanceof Registry) found.set(value.kind, value.names);
    }
    return new Map([...found].sort(([a], [b]) => a.localeCompare(b)));
  }

  render(root = "SystemConfig"): string {
    this.shown = new Map();
    const body = this.value({ kind: "ref", name: root }, { indent: "", seen: [], depth: 0, owner: root, path: "" });
    return [...this.header(root), ...body.lines, ""].join("\n");
  }

  private header(root: string): string[] {
    return [
      "// A witness config, generated by `witness config template`.",
      "//",
      `// Every field witness understands, with the doc comment from the type that declares it (\`${root}\`).`,
      "// Keep the ones your product has and delete the rest: only `name`, `root` and `services` are required.",
      "// Comments are part of the format, so these can stay.",
      "//",
      '// "…" is a value to fill in; "<name>" is a key you choose. A type used in more than one place is',
      "// spelled out the first time and pointed at after that.",
      "//",
      "// This was generated from the source of the copy that printed it, so it is never out of date with",
      "// the code that reads it — regenerate after an upgrade rather than editing an old copy.",
      "//",
      "// For the commands a finished config gives you: witness --config <file> help",
      "//",
      "// Providers registered in this copy, by kind:",
      ...[...this.registered].map(([kind, names]) => `//   ${kind.padEnd(8)} ${names.join(", ") || "none"}`),
      "",
    ];
  }

  /**
   * One value.
   *
   * `note` is what belongs on the same line as the value rather than above it — the alternatives of a
   * union, the choices for a provider — because the line above already carries the field's own doc.
   */
  private value(model: TypeModel, at: Where): Rendered {
    if (at.depth > this.maxDepth) return { lines: ["{}"], note: "nested deeper than this template goes" };

    switch (model.kind) {
      case "ref": {
        if (at.seen.includes(model.name)) return { lines: ["{}"], note: `a ${model.name} again — nest as deep as you need` };
        const already = this.shown.get(model.name);
        if (already !== undefined) return { lines: ["{}"], note: `a ${model.name} — spelled out under ${already}` };
        this.shown.set(model.name, at.path ? `"${at.path}"` : "the root");
        return this.value(this.types.declaration(model.name), { ...at, seen: [...at.seen, model.name], owner: model.name });
      }
      case "object": {
        const fields = model.fields.filter(f => f.name !== "*");
        const anyKey = model.fields.find(f => f.name === "*");
        if (!fields.length && anyKey) return this.value({ kind: "record", of: anyKey.type }, at);
        if (!fields.length) return { lines: ["{}"] };
        return { lines: this.block(fields, at) };
      }
      case "record": {
        const inner = this.value(model.of, { ...at, indent: `${at.indent}  `, depth: at.depth + 1, path: `${at.path}.<name>` });
        // The note goes on the opening line when the value is a block: a union's alternatives are worth
        // as much on `{` as on a scalar, and dropping them was losing half of what a template says.
        return { lines: ["{", `${at.indent}  "<name>": ${inner.lines[0]}${Template.tail(inner.note)}`, ...inner.lines.slice(1), `${at.indent}}`] };
      }
      case "array": {
        const inner = this.value(model.of, { ...at, indent: `${at.indent}  `, depth: at.depth + 1, path: `${at.path}[]` });
        return { lines: ["[", `${at.indent}  ${inner.lines[0]}${Template.tail(inner.note)}`, ...inner.lines.slice(1), `${at.indent}]`] };
      }
      case "union":
        return this.union(model.of, at);
      case "literal":
        return { lines: [model.json ? model.text : JSON.stringify(model.text)] };
      case "primitive":
        return { lines: [Template.example(model.name)] };
      case "opaque":
        return { lines: ["{}"], note: model.text };
    }
  }

  /** The fields of an object, each under its own comment. */
  private block(fields: TypeField[], at: Where): string[] {
    const lines = ["{"];
    fields.forEach((field, index) => {
      const rendered = this.value(field.type, {
        ...at,
        indent: `${at.indent}  `,
        depth: at.depth + 1,
        path: at.path ? `${at.path}.${field.name}` : field.name,
      });
      const note = this.hint(field, at.owner) ?? rendered.note;
      const multiline = rendered.lines.length > 1;
      for (const comment of Template.comments(field, multiline ? note : undefined)) lines.push(`${at.indent}  // ${comment}`);
      const comma = index === fields.length - 1 ? "" : ",";
      lines.push(`${at.indent}  ${JSON.stringify(field.name)}: ${rendered.lines[0]}${multiline ? "" : comma + Template.tail(note)}`);
      if (multiline) {
        lines.push(...rendered.lines.slice(1, -1), `${rendered.lines[rendered.lines.length - 1]}${comma}`);
      }
    });
    lines.push(`${at.indent}}`);
    return lines;
  }

  /**
   * A union: show the richest shape, and say what else is allowed.
   *
   * Spelling out every branch of `string | { … }` would make the template unreadable, and what a template
   * is for is the shape you are most likely to want, with the rest named.
   */
  private union(options: TypeModel[], at: Where): Rendered {
    const literals = options.filter(o => o.kind === "literal");
    if (literals.length === options.length) {
      return { lines: this.value(options[0], at).lines, note: `one of: ${literals.map(l => l.text).join(" | ")}` };
    }
    const best = [...options].sort((a, b) => this.weight(b) - this.weight(a))[0];
    const rendered = this.value(best, at);
    const others = options.filter(o => o !== best).map(o => Template.name(o));
    return { lines: rendered.lines, note: others.length ? `or: ${others.join(" | ")}` : rendered.note };
  }

  /** The choices for a `provider` field, from the registry that answers for this type. */
  private hint(field: TypeField, owner: string): string | undefined {
    if (field.name !== "provider") return undefined;
    for (const [kind, names] of this.registered) {
      if (owner.toLowerCase().startsWith(kind)) return `one of: ${names.join(", ")}`;
    }
    return undefined;
  }

  /** How much shape an option carries, for picking the branch of a union worth showing. */
  private weight(model: TypeModel): number {
    if (model.kind === "object") return 10 + model.fields.length;
    if (model.kind === "ref") return this.types.has(model.name) ? this.weight(this.types.declaration(model.name)) : 0;
    if (model.kind === "record" || model.kind === "array") return 5;
    return 0;
  }

  private static name(model: TypeModel): string {
    switch (model.kind) {
      case "primitive":
        return model.name;
      case "literal":
        return JSON.stringify(model.text);
      case "ref":
        return model.name;
      case "record":
        return `{ "<name>": ${Template.name(model.of)} }`;
      case "array":
        return `${Template.name(model.of)}[]`;
      case "object":
        return `{ ${model.fields.map(f => f.name).join(", ")} }`;
      case "union":
        return model.of.map(Template.name).join(" | ");
      case "opaque":
        return model.text;
    }
  }

  private static comments(field: TypeField, note?: string): string[] {
    return Template.wrapText([field.optional ? undefined : "required.", field.doc, note].filter(Boolean).join(" "), 108);
  }

  private static wrapText(text: string, width: number): string[] {
    if (!text) return [];
    const lines: string[] = [];
    let line = "";
    for (const word of text.split(/\s+/)) {
      if (line && `${line} ${word}`.length > width) {
        lines.push(line);
        line = word;
      } else line = line ? `${line} ${word}` : word;
    }
    if (line) lines.push(line);
    return lines;
  }

  private static tail(note?: string): string {
    return note ? `  // ${note}` : "";
  }

  private static example(primitive: string): string {
    switch (primitive) {
      case "number":
        return "0";
      case "boolean":
        return "false";
      case "null":
      case "undefined":
        return "null";
      case "string":
        return '"…"';
      default:
        return "{}";
    }
  }
}

/** Where in the document a value is being rendered — for indentation, cycles and "shown under" notes. */
type Where = { indent: string; seen: string[]; depth: number; owner: string; path: string };

type Rendered = { lines: string[]; note?: string };
