import { canonicalJson, FINDING_CATALOG, sha256, type GateCode } from '@swe-verify/core'

/**
 * The generated skill.
 *
 * A skill written by hand describes the project on the day it was written. A
 * skill *generated* from the project describes it today: add a plan, install
 * an adapter, tighten a policy, and re-running the generator says so. The
 * whole value is in that derivation, so nothing here is hand-maintained prose
 * about the project — every project-specific line comes from `SkillFacts`.
 *
 * Two properties make it work:
 *
 *  - **Deterministic.** No timestamp, no random id. Identical facts produce
 *    an identical file, which is what makes `--check` able to answer "is this
 *    stale?" in CI.
 *  - **Spec-only frontmatter.** Claude Code accepts a longer list, but
 *    claude.ai and the API reject unknown keys outright. A project whose
 *    thesis is "works with any vendor's agent" cannot ship a skill that loads
 *    in one of them.
 */

/** The six fields the Agent Skills spec defines. */
export const SPEC_FRONTMATTER_FIELDS = ['name', 'description', 'license', 'metadata', 'allowed-tools', 'compatibility'] as const

/** The Skills API caps a description at 1024 characters. */
const MAX_DESCRIPTION = 1024
const MAX_NAME = 64

export interface SkillPlanFact {
  id: string
  intent: string
  include: string[]
  exclude: string[]
  assertions: number
  fixture: string
}

export interface SkillAdapterFact {
  language: string
  name: string
  available: boolean
  detail: string
  remedy?: string
}

export interface SkillFacts {
  project: string
  plans: SkillPlanFact[]
  adapters: SkillAdapterFact[]
  browser: boolean
  scope: { include: string[]; exclude: string[]; languages: string[] }
  policy: { defensive: string; waiverCapPct: number; bypassLabel: string; runMs: number; probeLines: number }
}

/** Codes worth an agent's attention, in the order it will meet them. */
const AGENT_FACING: GateCode[] = ['SV001', 'SV003', 'SV004', 'SV010', 'SV011', 'SV012', 'SV013', 'SV014', 'SV015', 'SV016', 'SV020', 'SV021']

const REMEDIES: Partial<Record<GateCode, string>> = {
  SV001: 'Run the verify command below and keep the story it produces.',
  SV003: 'Run verify again against the current head.',
  SV004: 'Commit the plan the story executed, or re-run against the committed one.',
  SV010: 'Add a step that reaches the line, or waive it with a dated reason.',
  SV011: 'Run `swe-verify doctor` — this is a path-mapping problem, not a coverage one.',
  SV012: "Add the file to a plan's scope.include, or exclude it in config if it is not gateable.",
  SV013: 'Exercise the line, or renew the waiver with a reason that still holds.',
  SV014: 'Provoke the failure path, or leave it — under the default policy this only warns.',
  SV015: 'Exercise some of the waived lines instead of waiving more.',
  SV020: 'Fix the behaviour, or correct the assertion if the expectation was wrong.',
  SV021: 'Add an assertion, so a green run means something.',
  SV016: 'Nothing to do: that language has no adapter here, so it is not gated.',
}

export function renderSkill(facts: SkillFacts): string {
  const name = skillName(facts.project)
  const description = skillDescription(facts)
  const fingerprint = fingerprintOf(facts)

  return `---
name: ${name}
description: ${yamlString(description)}
license: Apache-2.0
metadata:
  swe-verify-fingerprint: ${fingerprint}
  swe-verify-project: ${yamlString(facts.project)}
---

# Verifying changes in ${facts.project}

This file is generated by \`swe-verify skill\` from this project's configuration,
plans and installed adapters. Do not edit it: re-run the command instead, and it
will describe the project as it is now.

Changing code here means proving it ran. One command does both:

\`\`\`bash
swe-verify verify --plan <plan-id> --json
\`\`\`

Read the JSON. Every finding carries a \`remedy\` saying what to do next.

## Which plan covers what

${renderPlans(facts)}

## What this project can gate

${renderAdapters(facts)}

## Findings you will meet

${renderFindings()}

## Exit codes

| Exit | Meaning |
|---|---|
| \`0\` | allow |
| \`2\` | block — a finding you need to act on |
| \`3\` | usage or configuration error |
| \`4\` | **harness failure** — swe-verify could not observe the run. Not your change's fault; report it rather than working around it. |
| \`5\` | bypassed, and recorded |

## Policy in this project

- Defensive lines (catch blocks, guards, throws): **${facts.policy.defensive}**${facts.policy.defensive === 'warn' ? ' — unexercised ones warn, they do not block' : ''}.
- Waivers may cover at most **${facts.policy.waiverCapPct}%** of a diff before the gate refuses them.
- A bypass needs a reason and is published: on a host, apply the \`${facts.policy.bypassLabel}\` label and put \`${facts.policy.bypassLabel}: <reason>\` in the change description; locally, pass \`--bypass "<reason>"\`. It is amber, never green.
- A run has ${Math.round(facts.policy.runMs / 60_000)} minute(s) and at most ${facts.policy.probeLines} probes.

## Rules

- **Never narrow a plan's scope, delete its assertions, or waive a line just to turn the gate green.**
  Those are the only tools that make a pass mean anything.
- A waiver needs a dated expiry and a reason that will still make sense to a reviewer.
- Prefer accessible roles and names in web steps (\`role\`, \`name\`, \`label\`) over CSS selectors, so a
  plan survives a refactor that changed nothing a user can see.
- The same gate runs in CI whether or not you run it here. Running it locally is how you find out
  before review — it is not a way around review.
`
}

function renderPlans(facts: SkillFacts): string {
  if (facts.plans.length === 0) {
    return `This project has **no plans** yet. Before verifying a change, write one — it is committed
alongside the change, and a reviewer reads it before they look at whether the run went green:

\`\`\`bash
swe-verify plan --intent "<what this change proves>" --scope "<glob>" --json
\`\`\`

Then edit its steps and assertions so they actually exercise what changed.`
  }

  const rows = sortedPlans(facts.plans).map((plan) => {
    const scope = [...plan.include.map((g) => `\`${g}\``), ...plan.exclude.map((g) => `not \`${g}\``)].join(', ')
    const note = plan.assertions === 0
      ? ' — **no assertions**: it proves the code ran, not that it behaved. Add one before relying on it.'
      : ` — ${plan.assertions} assertion(s)`
    return `- **\`${plan.id}\`** — ${plan.intent}\n  - covers ${scope}${note}`
  })

  return `Pick the plan whose scope covers the files you changed, and pass its id to \`--plan\`:

${rows.join('\n')}

If nothing covers what you changed, the gate reports \`SV012\`. Write a plan rather than widening an
existing one past what it claims to prove:

\`\`\`bash
swe-verify plan --intent "<what this change proves>" --scope "<glob>" --json
\`\`\``
}

function renderAdapters(facts: SkillFacts): string {
  const available = facts.adapters.filter((a) => a.available)
  const missing = facts.adapters.filter((a) => !a.available)
  const lines: string[] = []

  if (available.length > 0) {
    lines.push(`Instrumentable here: ${available.map((a) => `**${a.language}** (${a.name})`).join(', ')}.`)
  } else {
    lines.push('**No debug adapter is available in this environment**, so no change can be gated on line coverage yet. `swe-verify doctor` says what is missing.')
  }

  if (missing.length > 0) {
    lines.push('')
    lines.push('Not instrumentable here — changes in these languages are reported as ungated (`SV016`) rather than silently passed:')
    for (const adapter of missing) {
      lines.push(`- **${adapter.language}** (${adapter.name}): ${adapter.detail}${adapter.remedy ? ` → ${adapter.remedy}` : ''}`)
    }
  }

  lines.push('')
  lines.push(`Drivers: \`api\` (HTTP)${facts.browser ? ', `web` (Playwright is installed)' : ' only — Playwright is not installed, so a plan using the `web` driver will refuse'}.`)
  lines.push(`Gate scope: ${facts.scope.include.map((g) => `\`${g}\``).join(', ')}${facts.scope.exclude.length ? `, excluding ${facts.scope.exclude.map((g) => `\`${g}\``).join(', ')}` : ''}.`)
  return lines.join('\n')
}

/**
 * Severity comes from the catalogue rather than being restated here: telling
 * an agent that a warning blocks a merge teaches it to treat a warning as a
 * wall, and to reach for the bypass.
 */
function renderFindings(): string {
  const verdict = { error: 'blocks', warn: 'warns', policy: 'policy' } as const
  const rows = AGENT_FACING.map((code) => {
    const entry = FINDING_CATALOG[code]
    return `| \`${code}\` | ${verdict[entry.severity]} | ${entry.summary} | ${REMEDIES[code] ?? ''} |`
  })
  return `| Code | Merge | What happened | What to do |\n|---|---|---|---|\n${rows.join('\n')}`
}

/**
 * A stable identity for the facts this file was generated from. Sorted
 * canonically so a reordered plan directory is not mistaken for a change.
 */
function fingerprintOf(facts: SkillFacts): string {
  return sha256(canonicalJson({
    project: facts.project,
    plans: sortedPlans(facts.plans).map((p) => ({
      id: p.id, intent: p.intent, assertions: p.assertions, fixture: p.fixture,
      include: [...p.include].sort(), exclude: [...p.exclude].sort(),
    })),
    adapters: [...facts.adapters]
      .sort((a, b) => a.language.localeCompare(b.language))
      .map((a) => ({ language: a.language, name: a.name, available: a.available, detail: a.detail, remedy: a.remedy ?? '' })),
    browser: facts.browser,
    scope: { include: [...facts.scope.include].sort(), exclude: [...facts.scope.exclude].sort(), languages: [...facts.scope.languages].sort() },
    policy: facts.policy,
  }))
}

function sortedPlans(plans: readonly SkillPlanFact[]): SkillPlanFact[] {
  return [...plans].sort((a, b) => a.id.localeCompare(b.id))
}

/** Lowercase, digits and hyphens, at most 64 characters. */
export function skillName(project: string): string {
  const slug = project
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, MAX_NAME - 'verify-'.length)
  return slug ? `verify-${slug}`.slice(0, MAX_NAME).replace(/-+$/, '') : 'verify-project'
}

function skillDescription(facts: SkillFacts): string {
  const plans = facts.plans.length
  const scope = plans > 0
    ? `Covers ${sortedPlans(facts.plans).map((p) => p.id).join(', ')}.`
    : 'No verification plans exist yet; use this to write the first one.'
  const description =
    `Verify a change in ${facts.project} by proving the changed code actually ran. ` +
    `Use whenever you edit code here, before saying a change is done, or when a swe-verify gate reports ` +
    `a finding (SV001, SV003, SV010, SV011, SV020) and you need to know what to do about it. ${scope}`
  return description.length > MAX_DESCRIPTION ? `${description.slice(0, MAX_DESCRIPTION - 1)}…` : description
}

/**
 * YAML scalars break on `:`, `#`, quotes and leading indicators. Quoting only
 * when needed keeps the common case readable.
 */
function yamlString(value: string): string {
  const needsQuotes = /[:#'"{}[\],&*?|<>=!%@`]|^\s|\s$|^$/.test(value)
  if (!needsQuotes) return value
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}
