import { canonicalJson, FINDING_CATALOG, sha256, type GateCode } from '@swe-verify/core'

/**
 * The generated skill.
 *
 * A skill written by hand describes the project on the day it was written. A
 * skill *generated* from the project describes it today: add a plan, install
 * an adapter, tighten a policy, and re-running the generator says so. The
 * whole value is in that derivation, so nothing here is hand-maintained prose
 * about the project — every project-specific line comes from `SkillFacts`.
 *
 * Two properties make it work:
 *
 *  - **Deterministic.** No timestamp, no random id. Identical facts produce
 *    an identical file, which is what makes `--check` able to answer "is this
 *    stale?" in CI.
 *  - **Spec-only frontmatter.** Claude Code accepts a longer list, but
 *    claude.ai and the API reject unknown keys outright. A project whose
 *    thesis is "works with any vendor's agent" cannot ship a skill that loads
 *    in one of them.
 */

/** The six fields the Agent Skills spec defines. */
export const SPEC_FRONTMATTER_FIELDS = ['name', 'description', 'license', 'metadata', 'allowed-tools', 'compatibility'] as const

/** The Skills API caps a description at 1024 characters. */
const MAX_DESCRIPTION = 1024
const MAX_NAME = 64

export interface SkillPlanFact {
  id: string
  intent: string
  include: string[]
  exclude: string[]
  assertions: number
  fixture: string
}

export interface SkillAdapterFact {
  language: string
  name: string
  available: boolean
  detail: string
  remedy?: string
}

export interface SkillFacts {
  project: string
  plans: SkillPlanFact[]
  adapters: SkillAdapterFact[]
  browser: boolean
  scope: { include: string[]; exclude: string[]; languages: string[] }
  /** Assertion kinds this build ships, so the skill cannot describe one it lacks. */
  assertionKinds: string[]
  policy: { defensive: string; waiverCapPct: number; bypassLabel: string; runMs: number; probeLines: number }
}

/** Codes worth an agent's attention, in the order it will meet them. */
const AGENT_FACING: GateCode[] = ['SV001', 'SV003', 'SV004', 'SV010', 'SV011', 'SV012', 'SV013', 'SV014', 'SV015', 'SV016', 'SV020', 'SV021']

const REMEDIES: Partial<Record<GateCode, string>> = {
  SV001: 'Run the verify command below and keep the story it produces.',
  SV003: 'Run verify again against the current head.',
  SV004: 'Commit the plan the story executed, or re-run against the committed one.',
  SV010: 'Add a step that reaches the line, or waive it with a dated reason.',
  SV011: 'Run `swe-verify doctor` — this is a path-mapping problem, not a coverage one.',
  SV012: "Add the file to a plan's scope.include, or exclude it in config if it is not gateable.",
  SV013: 'Exercise the line, or renew the waiver with a reason that still holds.',
  SV014: 'Provoke the failure path, or leave it — under the default policy this only warns.',
  SV015: 'Exercise some of the waived lines instead of waiving more.',
  SV020: 'Fix the behaviour, or correct the assertion if the expectation was wrong.',
  SV021: 'Add an assertion, so a green run means something.',
  SV016: 'Nothing to do: that language has no adapter here, so it is not gated.',
}

export function renderSkill(facts: SkillFacts): string {
  const name = skillName(facts.project)
  const description = skillDescription(facts)
  const fingerprint = fingerprintOf(facts)

  return `---
name: ${name}
description: ${yamlString(description)}
license: Apache-2.0
metadata:
  swe-verify-fingerprint: ${fingerprint}
  swe-verify-project: ${yamlString(facts.project)}
---

# Verifying changes in ${facts.project}

Generated by \`swe-verify skill\` from this project's config, committed plans and installed
adapters. Do not edit — re-run the command and it will describe the project as it is now.

Every step is a command. Pass \`--json\` and read the JSON; never parse prose.

## 1. Pick the plan

${renderPlans(facts)}

## 2. Prove it, and film it

\`\`\`bash
swe-verify verify --plan <plan-id> --record --json
\`\`\`

One command: instruments every changed line, brings the fixture up, drives the plan, evaluates
the gate. \`--record\` adds a captioned MP4 to \`story.artifacts\`.

**\`--record\` needs the plan to say what to film.** Steps with \`"driver": "web"\` film themselves —
the page is the evidence. A change with no screen has to name the commands worth watching, in a
\`record\` block:

\`\`\`json
"record": {
  "terminal": {
    "steps": [
      { "caption": "BEFORE — the test fails on a cancelled context",
        "command": "go test ./pkg/... -run TestThing", "waitMs": 30000 },
      { "caption": "the one-line fix", "command": "git diff -U1" }
    ]
  }
}
\`\`\`

Each beat becomes its own clip with its caption rendered as a **card spliced in front of it** —
never typed into the shell, where a \`# comment\` would be indistinguishable from the program's
own output. Each beat is a fresh shell, so beats must be independent commands.

A plan that declares nothing filmable exits \`3\`: recording was asked for and there was nothing to
record, and a green verdict with no film is what recording exists to prevent.

| Exit | Meaning | Next move |
|---|---|---|
| \`0\` | allow | go to step 3 |
| \`2\` | block | act on each finding's \`remedy\` — never weaken the plan |
| \`3\` | usage or config error | fix the plan or config |
| \`4\` | **harness failure** | swe-verify could not observe. Not your change's fault; run \`swe-verify doctor\` and report it |
| \`5\` | bypassed | recorded and amber, never green |

### Bringing the app up

The \`fixture\` says how. Three kinds:

\`\`\`json
"fixture": { "kind": "process", "language": "py", "program": "server.py",
             "file": "app/server.py", "awaitExit": true }
\`\`\`

- **\`process\`** starts the program under a debugger. \`file\` locates the fixture and its
  directory becomes the working directory; **\`program\` is resolved inside that directory**, so it
  is usually just the basename — naming the same repo-relative path in both doubles the prefix.
  Go takes a package (\`"."\` with \`"mode": "test"\`), Java a class. \`awaitExit: true\` for a job or
  test binary; leave it off for a server, which never exits.
- **\`none\`** for an app already running — set \`baseUrl\`, and \`attach\` if a debug port is open.
- **\`compose\`** for a stack: \`file\` is the compose file, \`service\` and \`port\` name the container
  port that \`{port}\` resolves to, and \`build: true\` rebuilds first.

\`ready\` holds the app up until it serves — \`[{ "http": "http://127.0.0.1:{port}/health", "status": 200, "timeoutMs": 30000 }]\`.
Without it a plan starts driving a process that has not finished booting.

### Make it prove behaviour, not just execution

Without an assertion a green run says only that the code ran — that is \`SV021\`. Which kind fits
depends on what the fixture is:

${renderAssertionKinds(facts)}

An assertion anchors to a step with \`afterStep\`. A process fixture drives itself and has no
steps, so use \`afterStep: 0\` — it anchors to the run.

## 3. Film the reproduction too

A recording of the working state proves nothing on its own — a reader cannot tell a fix from a
film of a healthy system. What convinces is the pair.

\`\`\`bash
git stash                                        # or: git checkout <base>
swe-verify run --plan <plan-id> --record --json  # the bug, reproduced
git stash pop
\`\`\`

Which recording you get is decided by **what is checked out** — the tool does not revert files
for you, because a revert that dies mid-run leaves a wrecked working tree. Each file names its
own branch and commit, and is marked \`-dirty\` when the tree had uncommitted changes.

**Checking out the base is wrong when the fix and its test landed together.** Reverting the
commit reverts the strengthened assertion too, so the old weak test passes against the old buggy
code and the recording shows green — a reproduction that reproduces nothing. Revert only the
production line instead, and keep the test that detects the bug:

**Commit your fix before you film anything.** \`git checkout HEAD -- <file>\` restores the file as
\`HEAD\` has it — so if the fix is still uncommitted, "putting it back" overwrites it with the
original and the work is gone. There is no stash, no dangling blob, nothing to recover: this has
already destroyed a finished fix once.

\`\`\`bash
git add -A && git commit -m "<the fix>"           # first, always
git checkout HEAD~1 -- <the-source-file>          # not the test
swe-verify run --plan <plan-id> --record --json
git checkout HEAD -- <the-source-file>            # now this restores the fix
\`\`\`

Then read the transcript before you attach anything. If the "before" run passed, you filmed a
healthy system and have no reproduction.

A reproduction **must not end on the working state**: the same plan runs against both builds, so
a reconciling final beat makes the pair indistinguishable at the frame a reviewer scrubs to.

## 4. Collect the artefacts

\`\`\`bash
swe-verify show --run <run-id> --json
\`\`\`

\`\`\`
.swe-verify/runs/<run-id>/
  story.json                 the sealed evidence
  artifacts/video/run.mp4    the recording          readableBy: [human]
  artifacts/…                what the agent reads   readableBy: [agent]
  logs/harness.log           what the harness did
  viewer.html                30-second audit, offline
\`\`\`

## 5. Open the PR

\`\`\`bash
gh repo fork <owner>/<repo> --clone=false   # once, if you do not own the repo
git remote add fork https://github.com/<you>/<repo>.git
git push -u fork <branch>
gh pr create --repo <you>/<repo> --base <the fork's default branch> --head <branch> \\
  --title "<title>" --body-file body.md
\`\`\`

Target **the fork's own default branch**, not the upstream project's — check it with
\`gh repo view <you>/<repo> --json defaultBranchRef\`, since it is \`master\` on older repositories.
\`--remote=false\` is rejected when a repository argument is given, so add the remote yourself.

Put a placeholder where each recording goes (\`BEFORE_VIDEO\`, \`AFTER_VIDEO\`). State what the
evidence shows — and if the pair shows no difference, say that rather than implying one.

## 6. Attach the recordings — needs a logged-in browser

**\`gh\` and a token cannot reach GitHub's \`user-attachments\` CDN**, so there is no CLI path for
this. A body referencing a local path renders nothing.

1. Open the PR in a browser already signed in to GitHub
   (\`document.querySelector('meta[name="user-login"]')?.content\` to confirm).
2. Upload each file into the **"Paste, drop, or click to add files"** control.
3. Wait for \`https://github.com/user-attachments/assets/…\` to appear, one per file.
4. **Clear the box** so no stray comment posts.
5. Substitute the URLs into the body and publish:

\`\`\`bash
gh api -X PATCH repos/<owner>/<repo>/pulls/<n> -F body=@body.md
\`\`\`

## 7. Verify the evidence is really there

Not in a browser. \`video.readyState\` reports \`0\` on perfectly good attachments whenever the
page is busy — two agents chased that false failure and nearly reported working evidence as
broken. Ask whether the URL resolves to media bytes instead:

\`\`\`bash
for id in $(gh pr view <n> --repo <owner>/<repo> --json body -q .body \\
    | grep -o 'user-attachments/assets/[0-9a-f-]*' | cut -d/ -f3 | sort -u); do
  loc=$(curl -sI -H "Authorization: token $(gh auth token)" \\
        "https://github.com/user-attachments/assets/$id" | tr -d '\\r' | sed -n 's/^[Ll]ocation: //p')
  curl -sD - -o /dev/null --range 0-1023 "$loc" | grep -iE '^(HTTP|content-type|content-range)'
done
\`\`\`

A **ranged GET**, not \`curl -I\`: the redirect lands on a presigned URL signed for GET alone, so
a HEAD fails signature validation and answers \`403\` however healthy the file is.

\`206\` with \`video/mp4\` and a plausible \`content-range\` total is evidence. \`text/html\` means
the link resolves to a page, not a file. No output at all means the body still has its
placeholders in it.

## Findings you will meet

${renderFindings()}

## What this project can gate

${renderAdapters(facts)}

## Policy here

- Defensive lines (catch blocks, guards, throws): **${facts.policy.defensive}**${facts.policy.defensive === 'warn' ? ' — unexercised ones warn, they do not block' : ''}.
- Waivers may cover at most **${facts.policy.waiverCapPct}%** of a diff before the gate refuses them.
  A waiver is for a line that genuinely *cannot* run — a guard behind a check that already
  rejected the input, a branch reachable only on a platform this suite does not run on. It is not
  for a line that is merely awkward to reach; write the test instead. Both the reason and the
  expiry are required, because a waiver with neither is a permanent hole:

  \`\`\`json
  "coverage": {
    "policy": "all-executable",
    "waivers": [
      { "file": "src/parser.go", "lines": "296",
        "reason": "unreachable: the parser rejects malformed input before this fallback runs",
        "expires": "<YYYY-MM-DD>" }
    ]
  }
  \`\`\`

  \`lines\` is one number or a range (\`"296"\`, \`"296-298"\`); \`expires\` is a real ISO date you
  choose, and the gate warns as it approaches. Make the reason the argument for why the line
  cannot run — "hard to test" is not one, and a reviewer will read it as an excuse.
- A bypass needs a reason and is published: apply the \`${facts.policy.bypassLabel}\` label and put
  \`${facts.policy.bypassLabel}: <reason>\` in the change description, or pass \`--bypass "<reason>"\` locally.
- A run has ${Math.round(facts.policy.runMs / 60_000)} minute(s) and at most ${facts.policy.probeLines} probes.

## Rules

Each one comes from a recording that misled somebody.

- **A run that records nothing fails.** A green result with no video is the failure recording exists to prevent.
- **A caption narrates what the frame renders.** A value that was measured and which the app does not
  draw belongs in the probe dock, headed \`MEASURED\`.
- **Narration is never typed into the app or the shell.** Title cards are spliced in; the terminal
  shows commands and their output, nothing else.
- **Never narrow a plan's scope, delete its assertions, or waive a line to turn the gate green.**
  Those are the only tools that make a pass mean anything.
- **Do not bank a vacuous claim.** If a precondition was absent, or the pair shows no difference,
  say so on screen and in the PR.
- The same gate runs in **CI** whether or not you run it here. Running it locally is how you find
  out before review, not a way around it.

${renderLimits(facts)}
`
}

function renderPlans(facts: SkillFacts): string {
  if (facts.plans.length === 0) {
    return `This project has **no plans** yet. Before verifying a change, write one — it is committed
alongside the change, and a reviewer reads it before they look at whether the run went green:

\`\`\`bash
swe-verify plan --intent "<what this change proves>" --scope "<glob>" --json
\`\`\`

Then edit its steps and assertions so they actually exercise what changed.`
  }

  const rows = sortedPlans(facts.plans).map((plan) => {
    const scope = [...plan.include.map((g) => `\`${g}\``), ...plan.exclude.map((g) => `not \`${g}\``)].join(', ')
    const note = plan.assertions === 0
      ? ' — **no assertions**: it proves the code ran, not that it behaved. Add one before relying on it.'
      : ` — ${plan.assertions} assertion(s)`
    return `- **\`${plan.id}\`** — ${plan.intent}\n  - covers ${scope}${note}`
  })

  return `Pass the id of the plan whose scope covers the files you changed:

${rows.join('\n')}

If nothing covers what you changed, the gate reports \`SV012\`. Write a plan rather than widening an
existing one past what it claims to prove, then commit it with the change — a reviewer reads what
you set out to prove before they look at whether it went green:

\`\`\`bash
swe-verify plan --intent "<what this change proves>" --scope "<glob>" --json
\`\`\``
}

/**
 * The assertion kinds this build actually ships.
 *
 * An agent hit SV021 on a process fixture and had to read `packages/core` to
 * discover `terminal-match` existed: the skill named no assertion kind at
 * all, and the only example anywhere came from the `plan` skeleton, which
 * emits `http-status` — useless to a fixture that serves no HTTP. Without
 * this there is no documented way out of SV021 for a test or job fixture,
 * which is most backend work.
 */
function renderAssertionKinds(facts: SkillFacts): string {
  const shapes: Record<string, { when: string; example: string }> = {
    'terminal-match': {
      when: 'a process or test fixture — reads the transcript the recording produced',
      example: '{ "id": "a1", "kind": "terminal-match", "afterStep": 0,\n  "expect": { "contains": "--- PASS: TestThing", "absent": "FAIL" } }',
    },
    'http-status': {
      when: 'an API step',
      example: '{ "id": "a1", "kind": "http-status", "afterStep": 1, "expect": { "status": 400 } }',
    },
    'http-json': {
      when: 'a field in an API response',
      example: '{ "id": "a2", "kind": "http-json", "afterStep": 3,\n  "expect": { "path": "body.todos.0.text", "equals": "buy milk" } }\n\n  // `path` reads headers too, which is how you assert on a binary response:\n  { "id": "a3", "kind": "http-json", "afterStep": 3,\n    "expect": { "path": "headers.content-type", "equals": "application/octet-stream" } }',
    },
    'ui-text': {
      when: 'what the page showed — evaluated from the story, so it works while recording',
      example: '{ "id": "a3", "kind": "ui-text", "afterStep": 5, "expect": { "visible": "Order confirmed" } }',
    },
  }

  const known = facts.assertionKinds.filter((k) => shapes[k])
  const unknown = facts.assertionKinds.filter((k) => !shapes[k])
  const blocks = known.map((kind) => {
    const shape = shapes[kind]!
    return `- \`${kind}\` — ${shape.when}\n\n  \`\`\`json\n  ${shape.example.replace(/\n/g, '\n  ')}\n  \`\`\``
  })
  if (unknown.length > 0) blocks.push(`- also available: ${unknown.map((k) => `\`${k}\``).join(', ')}`)
  if (blocks.length === 0) return 'This build ships no assertion kinds, so no plan here can prove behaviour.'

  return `${blocks.join('\n')}

\`terminal-match\` reads the same transcript a reviewer watches in the video, so a green assertion
and a green recording are one claim rather than two that happen to share a pull request.`
}

/** What the tooling cannot do here — derived, not a static disclaimer. */
function renderLimits(facts: SkillFacts): string {
  const lines = [
    '## What the tooling cannot do here',
    '',
    '- `docker compose down` has no `--rmi`, so a `build: true` fixture leaves one image per run.',
    '- Attaching video to a PR (step 6) has no CLI path.',
    '- Each filmed beat is a fresh shell, so a beat cannot depend on state a previous one set up.',
  ]
  const missing = facts.adapters.filter((a) => !a.available)
  if (missing.length > 0) {
    lines.push(`- No adapter for ${missing.map((a) => `**${a.language}**`).join(', ')}: changed lines there are`)
    lines.push('  reported as ungated (`SV016`) rather than silently passed.')
  }
  if (!facts.browser) {
    lines.push('- Playwright is not installed, so nothing can be filmed and a `web` plan will refuse.')
  }
  return lines.join('\n')
}

function renderAdapters(facts: SkillFacts): string {
  const available = facts.adapters.filter((a) => a.available)
  const missing = facts.adapters.filter((a) => !a.available)
  const lines: string[] = []

  if (available.length > 0) {
    lines.push(`Instrumentable here: ${available.map((a) => `**${a.language}** (${a.name})`).join(', ')}.`)
  } else {
    lines.push('**No debug adapter is available in this environment**, so no change can be gated on line coverage yet. `swe-verify doctor` says what is missing.')
  }

  if (missing.length > 0) {
    lines.push('')
    lines.push('Not instrumentable here — changes in these languages are reported as ungated (`SV016`) rather than silently passed:')
    for (const adapter of missing) {
      lines.push(`- **${adapter.language}** (${adapter.name}): ${adapter.detail}${adapter.remedy ? ` → ${adapter.remedy}` : ''}`)
    }
  }

  lines.push('')
  lines.push(`Drivers: \`api\` (HTTP)${facts.browser ? ', `web` (Playwright is installed)' : ' only — Playwright is not installed, so a plan using the `web` driver will refuse'}.`)
  lines.push(`Gate scope: ${facts.scope.include.map((g) => `\`${g}\``).join(', ')}${facts.scope.exclude.length ? `, excluding ${facts.scope.exclude.map((g) => `\`${g}\``).join(', ')}` : ''}.`)
  return lines.join('\n')
}

/**
 * Severity comes from the catalogue rather than being restated here: telling
 * an agent that a warning blocks a merge teaches it to treat a warning as a
 * wall, and to reach for the bypass.
 */
function renderFindings(): string {
  const verdict = { error: 'blocks', warn: 'warns', policy: 'policy' } as const
  const rows = AGENT_FACING.map((code) => {
    const entry = FINDING_CATALOG[code]
    return `| \`${code}\` | ${verdict[entry.severity]} | ${entry.summary} | ${REMEDIES[code] ?? ''} |`
  })
  return `| Code | Merge | What happened | What to do |\n|---|---|---|---|\n${rows.join('\n')}`
}

/**
 * A stable identity for the facts this file was generated from. Sorted
 * canonically so a reordered plan directory is not mistaken for a change.
 */
function fingerprintOf(facts: SkillFacts): string {
  return sha256(canonicalJson({
    project: facts.project,
    plans: sortedPlans(facts.plans).map((p) => ({
      id: p.id, intent: p.intent, assertions: p.assertions, fixture: p.fixture,
      include: [...p.include].sort(), exclude: [...p.exclude].sort(),
    })),
    adapters: [...facts.adapters]
      .sort((a, b) => a.language.localeCompare(b.language))
      .map((a) => ({ language: a.language, name: a.name, available: a.available, detail: a.detail, remedy: a.remedy ?? '' })),
    browser: facts.browser,
    assertionKinds: [...facts.assertionKinds].sort(),
    scope: { include: [...facts.scope.include].sort(), exclude: [...facts.scope.exclude].sort(), languages: [...facts.scope.languages].sort() },
    policy: facts.policy,
  }))
}

function sortedPlans(plans: readonly SkillPlanFact[]): SkillPlanFact[] {
  return [...plans].sort((a, b) => a.id.localeCompare(b.id))
}

/** Lowercase, digits and hyphens, at most 64 characters. */
export function skillName(project: string): string {
  const slug = project
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, MAX_NAME - 'verify-'.length)
  return slug ? `verify-${slug}`.slice(0, MAX_NAME).replace(/-+$/, '') : 'verify-project'
}

function skillDescription(facts: SkillFacts): string {
  const plans = facts.plans.length
  const scope = plans > 0
    ? `Covers ${sortedPlans(facts.plans).map((p) => p.id).join(', ')}.`
    : 'No verification plans exist yet; use this to write the first one.'
  const description =
    `Verify a change in ${facts.project} by proving the changed code actually ran. ` +
    `Use whenever you edit code here, before saying a change is done, or when a swe-verify gate reports ` +
    `a finding (SV001, SV003, SV010, SV011, SV020) and you need to know what to do about it. ${scope}`
  return description.length > MAX_DESCRIPTION ? `${description.slice(0, MAX_DESCRIPTION - 1)}…` : description
}

/**
 * YAML scalars break on `:`, `#`, quotes and leading indicators. Quoting only
 * when needed keeps the common case readable.
 */
function yamlString(value: string): string {
  const needsQuotes = /[:#'"{}[\],&*?|<>=!%@`]|^\s|\s$|^$/.test(value)
  if (!needsQuotes) return value
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}
