import { canonicalJson, FINDING_CATALOG, sha256, type GateCode } from '@swe-verify/core'

/**
 * The generated skill.
 *
 * A skill written by hand describes the project on the day it was written. A
 * skill *generated* from the project describes it today: add a plan, install
 * an adapter, tighten a policy, and re-running the generator says so. The
 * whole value is in that derivation, so nothing here is hand-maintained prose
 * about the project — every project-specific line comes from `SkillFacts`.
 *
 * Two properties make it work:
 *
 *  - **Deterministic.** No timestamp, no random id. Identical facts produce
 *    an identical file, which is what makes `--check` able to answer "is this
 *    stale?" in CI.
 *  - **Spec-only frontmatter.** Claude Code accepts a longer list, but
 *    claude.ai and the API reject unknown keys outright. A project whose
 *    thesis is "works with any vendor's agent" cannot ship a skill that loads
 *    in one of them.
 */

/** The six fields the Agent Skills spec defines. */
export const SPEC_FRONTMATTER_FIELDS = ['name', 'description', 'license', 'metadata', 'allowed-tools', 'compatibility'] as const

/** The Skills API caps a description at 1024 characters. */
const MAX_DESCRIPTION = 1024
const MAX_NAME = 64

export interface SkillPlanFact {
  id: string
  intent: string
  include: string[]
  exclude: string[]
  assertions: number
  fixture: string
}

export interface SkillAdapterFact {
  language: string
  name: string
  available: boolean
  detail: string
  remedy?: string
}

export interface SkillFacts {
  project: string
  plans: SkillPlanFact[]
  adapters: SkillAdapterFact[]
  browser: boolean
  scope: { include: string[]; exclude: string[]; languages: string[] }
  policy: { defensive: string; waiverCapPct: number; bypassLabel: string; runMs: number; probeLines: number }
}

/** Codes worth an agent's attention, in the order it will meet them. */
const AGENT_FACING: GateCode[] = ['SV001', 'SV003', 'SV004', 'SV010', 'SV011', 'SV012', 'SV013', 'SV014', 'SV015', 'SV016', 'SV020', 'SV021']

const REMEDIES: Partial<Record<GateCode, string>> = {
  SV001: 'Run the verify command below and keep the story it produces.',
  SV003: 'Run verify again against the current head.',
  SV004: 'Commit the plan the story executed, or re-run against the committed one.',
  SV010: 'Add a step that reaches the line, or waive it with a dated reason.',
  SV011: 'Run `swe-verify doctor` — this is a path-mapping problem, not a coverage one.',
  SV012: "Add the file to a plan's scope.include, or exclude it in config if it is not gateable.",
  SV013: 'Exercise the line, or renew the waiver with a reason that still holds.',
  SV014: 'Provoke the failure path, or leave it — under the default policy this only warns.',
  SV015: 'Exercise some of the waived lines instead of waiving more.',
  SV020: 'Fix the behaviour, or correct the assertion if the expectation was wrong.',
  SV021: 'Add an assertion, so a green run means something.',
  SV016: 'Nothing to do: that language has no adapter here, so it is not gated.',
}

export function renderSkill(facts: SkillFacts): string {
  const name = skillName(facts.project)
  const description = skillDescription(facts)
  const fingerprint = fingerprintOf(facts)

  return `---
name: ${name}
description: ${yamlString(description)}
license: Apache-2.0
metadata:
  swe-verify-fingerprint: ${fingerprint}
  swe-verify-project: ${yamlString(facts.project)}
---

# Verifying changes in ${facts.project}

Generated by \`swe-verify skill\` from this project's config, committed plans and installed
adapters. Do not edit — re-run the command and it will describe the project as it is now.

Every step is a command. Pass \`--json\` and read the JSON; never parse prose.

## 1. Pick the plan

${renderPlans(facts)}

## 2. Prove it, and film it

\`\`\`bash
swe-verify verify --plan <plan-id> --record --json
\`\`\`

One command: instruments every changed line, brings the fixture up, drives the plan, evaluates
the gate. \`--record\` adds a captioned MP4 to \`story.artifacts\`.

| Exit | Meaning | Next move |
|---|---|---|
| \`0\` | allow | go to step 3 |
| \`2\` | block | act on each finding's \`remedy\` — never weaken the plan |
| \`3\` | usage or config error | fix the plan or config |
| \`4\` | **harness failure** | swe-verify could not observe. Not your change's fault; run \`swe-verify doctor\` and report it |
| \`5\` | bypassed | recorded and amber, never green |

## 3. Film the reproduction too

A recording of the working state proves nothing on its own — a reader cannot tell a fix from a
film of a healthy system. What convinces is the pair.

\`\`\`bash
git stash                                        # or: git checkout <base>
swe-verify run --plan <plan-id> --record --json  # the bug, reproduced
git stash pop
\`\`\`

Which recording you get is decided by **what is checked out** — the tool does not revert files
for you, because a revert that dies mid-run leaves a wrecked working tree. Each file names its
own branch and commit, and is marked \`-dirty\` when the tree had uncommitted changes.

A reproduction **must not end on the working state**: the same plan runs against both builds, so
a reconciling final beat makes the pair indistinguishable at the frame a reviewer scrubs to.

## 4. Collect the artefacts

\`\`\`bash
swe-verify show --run <run-id> --json
\`\`\`

\`\`\`
.swe-verify/runs/<run-id>/
  story.json                 the sealed evidence
  artifacts/video/run.mp4    the recording          readableBy: [human]
  artifacts/…                what the agent reads   readableBy: [agent]
  logs/harness.log           what the harness did
  viewer.html                30-second audit, offline
\`\`\`

## 5. Open the PR

\`\`\`bash
gh pr create --base <base> --head <branch> --title "<title>" --body-file body.md
\`\`\`

Put a placeholder where each recording goes (\`BEFORE_VIDEO\`, \`AFTER_VIDEO\`). State what the
evidence shows — and if the pair shows no difference, say that rather than implying one.

## 6. Attach the recordings — needs a logged-in browser

**\`gh\` and a token cannot reach GitHub's \`user-attachments\` CDN**, so there is no CLI path for
this. A body referencing a local path renders nothing.

1. Open the PR in a browser already signed in to GitHub
   (\`document.querySelector('meta[name="user-login"]')?.content\` to confirm).
2. Upload each file into the **"Paste, drop, or click to add files"** control.
3. Wait for \`https://github.com/user-attachments/assets/…\` to appear, one per file.
4. **Clear the box** so no stray comment posts.
5. Substitute the URLs into the body and publish:

\`\`\`bash
gh api -X PATCH repos/<owner>/<repo>/pulls/<n> -F body=@body.md
\`\`\`

## 7. Verify the evidence rendered

\`\`\`js
[...document.querySelectorAll('video')].map(v => ({ readyState: v.readyState, duration: v.duration }))
\`\`\`

\`readyState === 4\` and a non-zero duration. A dead link is not evidence.

## Findings you will meet

${renderFindings()}

## What this project can gate

${renderAdapters(facts)}

## Policy here

- Defensive lines (catch blocks, guards, throws): **${facts.policy.defensive}**${facts.policy.defensive === 'warn' ? ' — unexercised ones warn, they do not block' : ''}.
- Waivers may cover at most **${facts.policy.waiverCapPct}%** of a diff before the gate refuses them.
- A bypass needs a reason and is published: apply the \`${facts.policy.bypassLabel}\` label and put
  \`${facts.policy.bypassLabel}: <reason>\` in the change description, or pass \`--bypass "<reason>"\` locally.
- A run has ${Math.round(facts.policy.runMs / 60_000)} minute(s) and at most ${facts.policy.probeLines} probes.

## Rules

Each one comes from a recording that misled somebody.

- **A run that records nothing fails.** A green result with no video is the failure recording exists to prevent.
- **A caption narrates what the frame renders.** A value that was measured and which the app does not
  draw belongs in the probe dock, headed \`MEASURED\`.
- **Narration is never typed into the app or the shell.** Title cards are spliced in; the terminal
  shows commands and their output, nothing else.
- **Never narrow a plan's scope, delete its assertions, or waive a line to turn the gate green.**
  Those are the only tools that make a pass mean anything.
- **Do not bank a vacuous claim.** If a precondition was absent, or the pair shows no difference,
  say so on screen and in the PR.
- The same gate runs in **CI** whether or not you run it here. Running it locally is how you find
  out before review, not a way around it.

${renderLimits(facts)}
`
}

function renderPlans(facts: SkillFacts): string {
  if (facts.plans.length === 0) {
    return `This project has **no plans** yet. Before verifying a change, write one — it is committed
alongside the change, and a reviewer reads it before they look at whether the run went green:

\`\`\`bash
swe-verify plan --intent "<what this change proves>" --scope "<glob>" --json
\`\`\`

Then edit its steps and assertions so they actually exercise what changed.`
  }

  const rows = sortedPlans(facts.plans).map((plan) => {
    const scope = [...plan.include.map((g) => `\`${g}\``), ...plan.exclude.map((g) => `not \`${g}\``)].join(', ')
    const note = plan.assertions === 0
      ? ' — **no assertions**: it proves the code ran, not that it behaved. Add one before relying on it.'
      : ` — ${plan.assertions} assertion(s)`
    return `- **\`${plan.id}\`** — ${plan.intent}\n  - covers ${scope}${note}`
  })

  return `Pass the id of the plan whose scope covers the files you changed:

${rows.join('\n')}

If nothing covers what you changed, the gate reports \`SV012\`. Write a plan rather than widening an
existing one past what it claims to prove, then commit it with the change — a reviewer reads what
you set out to prove before they look at whether it went green:

\`\`\`bash
swe-verify plan --intent "<what this change proves>" --scope "<glob>" --json
\`\`\``
}

/** What the tooling cannot do here — derived, not a static disclaimer. */
function renderLimits(facts: SkillFacts): string {
  const lines = [
    '## What the tooling cannot do here',
    '',
    '- `fixture.kind: "compose"` exits 3. Only `process` and `none` work, so an app needing container',
    '  provisioning has to be driven by a script rather than a plan.',
    '- Attaching video to a PR (step 6) has no CLI path.',
  ]
  const missing = facts.adapters.filter((a) => !a.available)
  if (missing.length > 0) {
    lines.push(`- No adapter for ${missing.map((a) => `**${a.language}**`).join(', ')}: changed lines there are`)
    lines.push('  reported as ungated (`SV016`) rather than silently passed.')
  }
  if (!facts.browser) {
    lines.push('- Playwright is not installed, so nothing can be filmed and a `web` plan will refuse.')
  }
  return lines.join('\n')
}

function renderAdapters(facts: SkillFacts): string {
  const available = facts.adapters.filter((a) => a.available)
  const missing = facts.adapters.filter((a) => !a.available)
  const lines: string[] = []

  if (available.length > 0) {
    lines.push(`Instrumentable here: ${available.map((a) => `**${a.language}** (${a.name})`).join(', ')}.`)
  } else {
    lines.push('**No debug adapter is available in this environment**, so no change can be gated on line coverage yet. `swe-verify doctor` says what is missing.')
  }

  if (missing.length > 0) {
    lines.push('')
    lines.push('Not instrumentable here — changes in these languages are reported as ungated (`SV016`) rather than silently passed:')
    for (const adapter of missing) {
      lines.push(`- **${adapter.language}** (${adapter.name}): ${adapter.detail}${adapter.remedy ? ` → ${adapter.remedy}` : ''}`)
    }
  }

  lines.push('')
  lines.push(`Drivers: \`api\` (HTTP)${facts.browser ? ', `web` (Playwright is installed)' : ' only — Playwright is not installed, so a plan using the `web` driver will refuse'}.`)
  lines.push(`Gate scope: ${facts.scope.include.map((g) => `\`${g}\``).join(', ')}${facts.scope.exclude.length ? `, excluding ${facts.scope.exclude.map((g) => `\`${g}\``).join(', ')}` : ''}.`)
  return lines.join('\n')
}

/**
 * Severity comes from the catalogue rather than being restated here: telling
 * an agent that a warning blocks a merge teaches it to treat a warning as a
 * wall, and to reach for the bypass.
 */
function renderFindings(): string {
  const verdict = { error: 'blocks', warn: 'warns', policy: 'policy' } as const
  const rows = AGENT_FACING.map((code) => {
    const entry = FINDING_CATALOG[code]
    return `| \`${code}\` | ${verdict[entry.severity]} | ${entry.summary} | ${REMEDIES[code] ?? ''} |`
  })
  return `| Code | Merge | What happened | What to do |\n|---|---|---|---|\n${rows.join('\n')}`
}

/**
 * A stable identity for the facts this file was generated from. Sorted
 * canonically so a reordered plan directory is not mistaken for a change.
 */
function fingerprintOf(facts: SkillFacts): string {
  return sha256(canonicalJson({
    project: facts.project,
    plans: sortedPlans(facts.plans).map((p) => ({
      id: p.id, intent: p.intent, assertions: p.assertions, fixture: p.fixture,
      include: [...p.include].sort(), exclude: [...p.exclude].sort(),
    })),
    adapters: [...facts.adapters]
      .sort((a, b) => a.language.localeCompare(b.language))
      .map((a) => ({ language: a.language, name: a.name, available: a.available, detail: a.detail, remedy: a.remedy ?? '' })),
    browser: facts.browser,
    scope: { include: [...facts.scope.include].sort(), exclude: [...facts.scope.exclude].sort(), languages: [...facts.scope.languages].sort() },
    policy: facts.policy,
  }))
}

function sortedPlans(plans: readonly SkillPlanFact[]): SkillPlanFact[] {
  return [...plans].sort((a, b) => a.id.localeCompare(b.id))
}

/** Lowercase, digits and hyphens, at most 64 characters. */
export function skillName(project: string): string {
  const slug = project
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, MAX_NAME - 'verify-'.length)
  return slug ? `verify-${slug}`.slice(0, MAX_NAME).replace(/-+$/, '') : 'verify-project'
}

function skillDescription(facts: SkillFacts): string {
  const plans = facts.plans.length
  const scope = plans > 0
    ? `Covers ${sortedPlans(facts.plans).map((p) => p.id).join(', ')}.`
    : 'No verification plans exist yet; use this to write the first one.'
  const description =
    `Verify a change in ${facts.project} by proving the changed code actually ran. ` +
    `Use whenever you edit code here, before saying a change is done, or when a swe-verify gate reports ` +
    `a finding (SV001, SV003, SV010, SV011, SV020) and you need to know what to do about it. ${scope}`
  return description.length > MAX_DESCRIPTION ? `${description.slice(0, MAX_DESCRIPTION - 1)}…` : description
}

/**
 * YAML scalars break on `:`, `#`, quotes and leading indicators. Quoting only
 * when needed keeps the common case readable.
 */
function yamlString(value: string): string {
  const needsQuotes = /[:#'"{}[\],&*?|<>=!%@`]|^\s|\s$|^$/.test(value)
  if (!needsQuotes) return value
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}
